### ISSUE TITLE
Increasing ram usage and tool never finishes. 

### ISSUE THREAD

**Issue by vincentcox** [EU-EDPS/website-evidence-collector#42]
Steps to reproduce:

Spawn a fresh Ubuntu 20.04 server (no GUI) VPS, install all the tools:

```sh
sudo apt update
sudo apt install nodejs -y 
sudo apt install npm -y
sudo apt install jq -y
sudo apt install chromium-browser -y
export PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser" # Fix the "browser not installed" bug, "stolen" from the Dockerfile
npm install --global https://github.com/EU-EDPS/website-evidence-collector/tarball/master 
mkdir output_dir
website-evidence-collector --output output_dir/vincentcox.com --json --max 3 https://vincentcox.com --overwrite -- --no-sandbox # Fix the chrome sandbox issue, found somewhere in the issue tracker
```

It keeps running and it keeps eating resources:
![rip memory](https://user-images.githubusercontent.com/9286611/99675612-b3be4c80-2a77-11eb-98bc-22b347ae5c61.png)
(_rip memory_)

Note that I am using the latest version from Github and that something might broke it in the Github version. But as explained in this issue (https://github.com/EU-EDPS/website-evidence-collector/issues/41), I cannot access the official download link of the stable version.

**Comment by rriemann-eu** [comment]
Do you have the same behavior when using chromium bundled with the puppeteer node package?

**Comment by vincentcox** [comment]
How can I use the puppeteer node package? (sorry, I have little experience with nodeJs).

I installed the latest stable version (mentioned in your reply in my previous issue), it's the same issue.

**Comment by vincentcox** [comment]
I have the same in docker, which is using the puppeteer node package. 

I removed the versions in the Dockerfile to get it working:

```Dockerfile
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      freetype-dev \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn \
```

**Comment by rriemann-eu** [comment]
It works for you now? Could you prepare a pull request then to help others?

Could you find out which versions you are using instead? I think I decided to fix the version numbers to have a more reproducable setup which is important for auditing.

**Comment by vincentcox** [comment]
Sorry, it was not clear in my previous answer. I am trying things out, but they all break if I test them on my website (also for a client, but I don't want to share that one as my website is a good "test" example). So I said that tried docker (using a modified version to get it working), but got the same bug.

**Comment by rriemann-eu** [comment]
In your example you have incuded `--max 3`, hence you scan also some other random pages of the same website. Can you please check if with only one page you still have the same behaviour? I would then try to reproduce your problem.

**Comment by vincentcox** [comment]
It's unfortunately the same (when using the installed version in my initial post but with --max 1). I gave up on docker because I get this error: 
```sh
error An unexpected error occurred: "EACCES: permission denied, scandir '/opt/website-evidence-collector/output/browser-profile'".
```

**Comment by vincentcox** [comment]
@rriemann-eu if you need more info to debug let me know!

**Comment by rriemann-eu** [comment]
So when I execute the following two commands, I do not get any error.

```sh
website-evidence-collector --output output_dir/vincentcox.com --json --max 1 https://vincentcox.com

website-evidence-collector --output output_dir/vincentcox.com2 --json --max 1 https://vincentcox.com -- --no-sandbox
```

I am using the latest version from master on opensuse. From the `inspection.yml`:

```yaml
script:
  host: mars.fritz.box
  version:
    npm: 0.4.0
    commit: v0.4.0-70-ga956e2d
  cmd_args: '--output output_dir/vincentcox.com --json --max 1 https://vincentcox.com'
  environment: {}
  node_version: v10.22.1
browser:
  name: Chromium
  version: HeadlessChrome/80.0.3987.0
  user_agent: >-
    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/72.0.3617.0 Safari/537.36
  platform:
    name: Linux
    version: 5.8.14-1-default
  extra_headers: {}
  preset_cookies: {}
start_time: 2020-11-24T11:30:47.957Z
end_time: 2020-11-24T11:31:00.650Z
```


Does your problem occurs with all websites?
